name: Dependency Updates

on:
  schedule:
    - cron: '0 0 * * *' # Run daily at midnight

jobs:
  dependency_updates:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Dependabot
        uses: github/dependabot-preview@v0.135.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
