name: Custom Workflow

on:
  push:
    branches:
      - main

jobs:
  custom_job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Step 1
        run: echo "Executing Step 1"

      - name: Step 2
        run: echo "Executing Step 2"

      - name: Step 3
        run: echo "Executing Step 3"
